name: "pages"
on:
  pull_request:
  push:
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: datakurre
    - run: nix-shell --run "make"
